name: Build ASN & IP Database

on:
  push:
    paths:
      - 'builder/**'
      - '.github/**'
  schedule:
    - cron: "16 13 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build & Push
        run: | 
          sudo apt-get install -y bgpdump
          ./builder/build_asn_country_db.sh
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add *.bz2
          git commit -m "Updated ASN & IP databases"
          git push
