name: Build ASN & IP Database

on:
  push:
    paths:
      - 'builder/**'
      - '.github/**'
  schedule:
    - cron: "16 13 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: sudo sudo apt-get install -y bgpdump

      - name: Build databases
        run: ./builder/build_asn_country_db.sh

      - name: Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Updated ASN & IP databases"
          git push
